# Generated by Django 4.2.7 on 2025-10-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=15)),
                ('state', models.CharField(default='unknown', max_length=50)),
                ('county', models.CharField(default='unknown', max_length=100)),
                ('pollutant', models.CharField(max_length=70)),
                ('value', models.FloatField()),
                ('units', models.CharField(default='unknown', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
