# Generated by Django 4.2.7 on 2025-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epa_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAqiData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=15)),
                ("state", models.CharField(default="unknown", max_length=50)),
                ("county", models.CharField(default="unknown", max_length=100)),
                ("pollutant", models.CharField(max_length=70)),
                ("value", models.FloatField()),
                ("units", models.CharField(default="unknown", max_length=100)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Site AQI Data",
                "verbose_name_plural": "Site AQI Data",
                "db_table": "site_aqi_data",
            },
        ),
    ]
