# Generated by Django 4.2.7 on 2025-10-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_app', '0002_siteaqidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=15)),
                ('state', models.CharField(default='unknown', max_length=50)),
                ('city', models.CharField(default='unknown', max_length=100)),
                ('county', models.CharField(default='unknown', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('no2_start_date', models.DateField(default='No NO2 Data')),
                ('co_start_date', models.DateField(default='No CO Data')),
                ('pm_start_date', models.DateField(default='No PM 2.5 Data')),
            ],
        ),
    ]
