# Generated by Django 4.2.7 on 2025-10-31 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epa_app', '0003_sitmetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sitMetaData',
            new_name='SiteMetaData',
        ),
    ]
