# Generated by Django 4.2.7 on 2025-10-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epa_app', '0004_rename_sitmetadata_sitemetadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemetadata',
            options={'verbose_name': 'Site Meta Data', 'verbose_name_plural': 'Site Meta Data'},
        ),
        migrations.AlterModelTable(
            name='sitemetadata',
            table='site_meta_data',
        ),
    ]
