# Generated by Django 4.2.7 on 2025-10-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_app', '0005_alter_sitemetadata_options_alter_sitemetadata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='co_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='no2_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='pm_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
